name: Update Domains

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run checks
        run: make check

      - name: Commit changes
        run: |
          if git diff --quiet -- chndomains.rsc; then
            echo "No generated changes."
            exit 0
          fi

          git config --global user.name "newco"
          git config --global user.email "newcoderlife@gmail.com"
          DATE=$(date +'%Y%m%d')
          git add chndomains.rsc
          git commit -m "chore: Update domains $DATE"
          git push
